#include <iostream>
#include <conio.h>
#include <windows.h>
using namespace std;
void Empty(char game[][350]) {
	for (int r = 0; r < 30; r++)
	{
		for (int c = 0; c < 350; c++)
		{
			game[r][c] = ' ';
		}
	}
}
void drawPlatform(char platform[][350], int platformR, int platformC) {
	for (int i = 0; i < 300; i++)
	{
		platform[platformR][platformC + i] = '=';

	}
}
void drawGame(char game[][350], int scrollCend, int scrollCstart, int scrollRstart, int scrollRend) {
	system("cls");
	for (int r = scrollRend; r < scrollRstart; r++)
	{
		for (int c = scrollCstart; c < scrollCend; c++)
		{
			cout << game[r][c];
		}
	}
}
/*void Border(char game[][350], int rBorder, int cBorder) {
	game[rBorder - 29][cBorder + 0] = '.';
	game[rBorder - 29][cBorder + 1] = '-';
	game[rBorder - 29][cBorder + 2] = '=';
	game[rBorder - 29][cBorder + 3] = '-';
	game[rBorder - 29][cBorder + 4] = '=';
	game[rBorder - 29][cBorder + 5] = '-';
	game[rBorder - 29][cBorder + 6] = '=';
	game[rBorder - 29][cBorder + 7] = '-';
	game[rBorder - 29][cBorder + 8] = '=';
	game[rBorder - 29][cBorder + 9] = '-';
	game[rBorder - 29][cBorder + 10] = '=';
	game[rBorder - 29][cBorder + 11] = '-';
	game[rBorder - 29][cBorder + 12] = '=';
	game[rBorder - 29][cBorder + 13] = '-';
	game[rBorder - 29][cBorder + 14] = '=';
	game[rBorder - 29][cBorder + 15] = '-';
	game[rBorder - 29][cBorder + 16] = '=';
	game[rBorder - 29][cBorder + 17] = '-';
	game[rBorder - 29][cBorder + 18] = '=';
	game[rBorder - 29][cBorder + 19] = '-';
	game[rBorder - 29][cBorder + 20] = '=';
	game[rBorder - 29][cBorder + 21] = '-';
	game[rBorder - 29][cBorder + 22] = '=';
	game[rBorder - 29][cBorder + 23] = '-';
	game[rBorder - 29][cBorder + 24] = '=';
	game[rBorder - 29][cBorder + 25] = '-';
	game[rBorder - 29][cBorder + 26] = '=';
	game[rBorder - 29][cBorder + 27] = '-';
	game[rBorder - 29][cBorder + 28] = '=';
	game[rBorder - 29][cBorder + 29] = '-';
	game[rBorder - 29][cBorder + 30] = '=';
	game[rBorder - 29][cBorder + 31] = '-';
	game[rBorder - 29][cBorder + 32] = '=';
	game[rBorder - 29][cBorder + 33] = '-';
	game[rBorder - 29][cBorder + 34] = '=';
	game[rBorder - 29][cBorder + 35] = '-';
	game[rBorder - 29][cBorder + 36] = '=';
	game[rBorder - 29][cBorder + 37] = '-';
	game[rBorder - 29][cBorder + 38] = '=';
	game[rBorder - 29][cBorder + 39] = '-';
	game[rBorder - 29][cBorder + 40] = '=';
	game[rBorder - 29][cBorder + 41] = '-';
	game[rBorder - 29][cBorder + 42] = '=';
	game[rBorder - 29][cBorder + 43] = '-';
	game[rBorder - 29][cBorder + 44] = '=';
	game[rBorder - 29][cBorder + 45] = '-';
	game[rBorder - 29][cBorder + 46] = '=';
	game[rBorder - 29][cBorder + 47] = '-';
	game[rBorder - 29][cBorder + 48] = '=';
	game[rBorder - 29][cBorder + 49] = '-';
	game[rBorder - 29][cBorder + 50] = '=';
	game[rBorder - 29][cBorder + 51] = '-';
	game[rBorder - 29][cBorder + 52] = '=';
	game[rBorder - 29][cBorder + 53] = '-';
	game[rBorder - 29][cBorder + 54] = '=';
	game[rBorder - 29][cBorder + 55] = '-';
	game[rBorder - 29][cBorder + 56] = '=';
	game[rBorder - 29][cBorder + 57] = '-';
	game[rBorder - 29][cBorder + 58] = '=';
	game[rBorder - 29][cBorder + 59] = '-';
	game[rBorder - 29][cBorder + 60] = '=';
	game[rBorder - 29][cBorder + 61] = '-';
	game[rBorder - 29][cBorder + 62] = '=';
	game[rBorder - 29][cBorder + 63] = '-';
	game[rBorder - 29][cBorder + 64] = '=';
	game[rBorder - 29][cBorder + 65] = '-';
	game[rBorder - 29][cBorder + 66] = '=';
	game[rBorder - 29][cBorder + 67] = '-';
	game[rBorder - 29][cBorder + 68] = '=';
	game[rBorder - 29][cBorder + 69] = '-';
	game[rBorder - 29][cBorder + 70] = '=';
	game[rBorder - 29][cBorder + 71] = '-';
	game[rBorder - 29][cBorder + 72] = '=';
	game[rBorder - 29][cBorder + 73] = '-';
	game[rBorder - 29][cBorder + 74] = '=';
	game[rBorder - 29][cBorder + 75] = '-';
	game[rBorder - 29][cBorder + 76] = '=';
	game[rBorder - 29][cBorder + 77] = '-';
	game[rBorder - 29][cBorder + 78] = '=';
	game[rBorder - 29][cBorder + 79] = '-';
	game[rBorder - 29][cBorder + 80] = '=';
	game[rBorder - 29][cBorder + 81] = '-';
	game[rBorder - 29][cBorder + 82] = '=';
	game[rBorder - 29][cBorder + 83] = '-';
	game[rBorder - 29][cBorder + 84] = '=';
	game[rBorder - 29][cBorder + 85] = '-';
	game[rBorder - 29][cBorder + 86] = '=';
	game[rBorder - 29][cBorder + 87] = '-';
	game[rBorder - 29][cBorder + 88] = '=';
	game[rBorder - 29][cBorder + 89] = '-';
	game[rBorder - 29][cBorder + 90] = '=';
	game[rBorder - 29][cBorder + 91] = '-';
	game[rBorder - 29][cBorder + 92] = '=';
	game[rBorder - 29][cBorder + 93] = '-';
	game[rBorder - 29][cBorder + 94] = '=';
	game[rBorder - 29][cBorder + 95] = '-';
	game[rBorder - 29][cBorder + 96] = '=';
	game[rBorder - 29][cBorder + 97] = '-';
	game[rBorder - 29][cBorder + 98] = '=';
	game[rBorder - 29][cBorder + 99] = '-';
	game[rBorder - 29][cBorder + 100] = '=';
	game[rBorder - 29][cBorder + 101] = '-';
	game[rBorder - 29][cBorder + 102] = '=';
	game[rBorder - 29][cBorder + 103] = '-';
	game[rBorder - 29][cBorder + 104] = '=';
	game[rBorder - 29][cBorder + 105] = '-';
	game[rBorder - 29][cBorder + 106] = '=';
	game[rBorder - 29][cBorder + 107] = '-';
	game[rBorder - 29][cBorder + 108] = '=';
	game[rBorder - 29][cBorder + 109] = '-';
	game[rBorder - 29][cBorder + 110] = '=';
	game[rBorder - 29][cBorder + 111] = '-';
	game[rBorder - 29][cBorder + 112] = '=';
	game[rBorder - 29][cBorder + 113] = '-';
	game[rBorder - 29][cBorder + 114] = '=';
	game[rBorder - 29][cBorder + 115] = '-';
	game[rBorder - 29][cBorder + 116] = '=';
	game[rBorder - 29][cBorder + 117] = '-';
	game[rBorder - 29][cBorder + 118] = '=';
	game[rBorder - 29][cBorder + 119] = '-';
	game[rBorder - 29][cBorder + 120] = '=';
	game[rBorder - 29][cBorder + 121] = '-';
	game[rBorder - 29][cBorder + 122] = '=';
	game[rBorder - 29][cBorder + 123] = '-';
	game[rBorder - 29][cBorder + 124] = '=';
	game[rBorder - 29][cBorder + 125] = '-';
	game[rBorder - 29][cBorder + 126] = '=';
	game[rBorder - 29][cBorder + 127] = '-';
	game[rBorder - 29][cBorder + 128] = '=';
	game[rBorder - 29][cBorder + 129] = '-';
	game[rBorder - 29][cBorder + 130] = '=';
	game[rBorder - 29][cBorder + 131] = '-';
	game[rBorder - 29][cBorder + 132] = '=';
	game[rBorder - 29][cBorder + 133] = '-';
	game[rBorder - 29][cBorder + 134] = '=';
	game[rBorder - 29][cBorder + 135] = '-';
	game[rBorder - 29][cBorder + 136] = '=';
	game[rBorder - 29][cBorder + 137] = '-';
	game[rBorder - 29][cBorder + 138] = '=';
	game[rBorder - 29][cBorder + 139] = '-';
	game[rBorder - 29][cBorder + 140] = '=';
	game[rBorder - 29][cBorder + 141] = '-';
	game[rBorder - 29][cBorder + 142] = '=';
	game[rBorder - 29][cBorder + 143] = '-';
	game[rBorder - 29][cBorder + 144] = '=';
	game[rBorder - 29][cBorder + 145] = '-';
	game[rBorder - 29][cBorder + 146] = '=';
	game[rBorder - 29][cBorder + 147] = '-';
	game[rBorder - 29][cBorder + 148] = '=';
	game[rBorder - 29][cBorder + 149] = '-';
	game[rBorder - 29][cBorder + 150] = '=';
	game[rBorder - 29][cBorder + 151] = '-';
	game[rBorder - 29][cBorder + 152] = '=';
	game[rBorder - 29][cBorder + 153] = '-';
	game[rBorder - 29][cBorder + 154] = '=';
	game[rBorder - 29][cBorder + 155] = '-';
	game[rBorder - 29][cBorder + 156] = '=';
	game[rBorder - 29][cBorder + 157] = '-';
	game[rBorder - 29][cBorder + 158] = '=';
	game[rBorder - 29][cBorder + 159] = '-';
	game[rBorder - 29][cBorder + 160] = '=';
	game[rBorder - 29][cBorder + 161] = '-';
	game[rBorder - 29][cBorder + 162] = '=';
	game[rBorder - 29][cBorder + 163] = '-';
	game[rBorder - 29][cBorder + 164] = '=';
	game[rBorder - 29][cBorder + 165] = '-';
	game[rBorder - 29][cBorder + 166] = '=';
	game[rBorder - 29][cBorder + 167] = '-';
	game[rBorder - 29][cBorder + 168] = '=';
	game[rBorder - 29][cBorder + 169] = '-';
	game[rBorder - 29][cBorder + 170] = '=';
	game[rBorder - 29][cBorder + 171] = '-';
	game[rBorder - 29][cBorder + 172] = '=';
	game[rBorder - 29][cBorder + 173] = '-';
	game[rBorder - 29][cBorder + 174] = '=';
	game[rBorder - 29][cBorder + 175] = '-';
	game[rBorder - 29][cBorder + 176] = '=';
	game[rBorder - 29][cBorder + 177] = '-';
	game[rBorder - 29][cBorder + 178] = '=';
	game[rBorder - 29][cBorder + 179] = '-';
	game[rBorder - 29][cBorder + 180] = '=';
	game[rBorder - 29][cBorder + 181] = '-';
	game[rBorder - 29][cBorder + 182] = '=';
	game[rBorder - 29][cBorder + 183] = '-';
	game[rBorder - 29][cBorder + 184] = '=';
	game[rBorder - 29][cBorder + 185] = '-';
	game[rBorder - 29][cBorder + 186] = '=';
	game[rBorder - 29][cBorder + 187] = '-';
	game[rBorder - 29][cBorder + 188] = '=';
	game[rBorder - 29][cBorder + 189] = '-';
	game[rBorder - 29][cBorder + 190] = '=';
	game[rBorder - 29][cBorder + 191] = '-';
	game[rBorder - 29][cBorder + 192] = '=';
	game[rBorder - 29][cBorder + 193] = '-';
	game[rBorder - 29][cBorder + 194] = '=';
	game[rBorder - 29][cBorder + 195] = '-';
	game[rBorder - 29][cBorder + 196] = '=';
	game[rBorder - 29][cBorder + 197] = '-';
	game[rBorder - 29][cBorder + 198] = '=';
	game[rBorder - 29][cBorder + 199] = '-';
	game[rBorder - 29][cBorder + 200] = '=';
	game[rBorder - 29][cBorder + 201] = '-';
	game[rBorder - 29][cBorder + 202] = '=';
	game[rBorder - 29][cBorder + 203] = '-';
	game[rBorder - 29][cBorder + 204] = '=';
	game[rBorder - 29][cBorder + 205] = '-';
	game[rBorder - 29][cBorder + 206] = '=';
	game[rBorder - 29][cBorder + 207] = '-';
	game[rBorder - 29][cBorder + 208] = '=';
	game[rBorder - 29][cBorder + 209] = '-';
	game[rBorder - 29][cBorder + 210] = '=';
	game[rBorder - 29][cBorder + 211] = '-';
	game[rBorder - 29][cBorder + 212] = '=';
	game[rBorder - 29][cBorder + 213] = '-';
	game[rBorder - 29][cBorder + 214] = '=';
	game[rBorder - 29][cBorder + 215] = '-';
	game[rBorder - 29][cBorder + 216] = '=';
	game[rBorder - 29][cBorder + 217] = '-';
	game[rBorder - 29][cBorder + 218] = '=';
	game[rBorder - 29][cBorder + 219] = '-';
	game[rBorder - 29][cBorder + 220] = '=';
	game[rBorder - 29][cBorder + 221] = '-';
	game[rBorder - 29][cBorder + 222] = '.';
	game[rBorder - 28][cBorder + 0] = '|';
	game[rBorder - 27][cBorder + 0] = '|';
	game[rBorder - 27][cBorder + 169] = '|';
	game[rBorder - 26][cBorder + 0] = '|';
	game[rBorder - 26][cBorder + 169] = '|';
	game[rBorder - 25][cBorder + 0] = '|';
	game[rBorder - 25][cBorder + 169] = '|';
	game[rBorder - 24][cBorder + 0] = '!';
	game[rBorder - 24][cBorder + 169] = '!';
	game[rBorder - 23][cBorder + 0] = ':';
	game[rBorder - 23][cBorder + 169] = ':';
	game[rBorder - 22][cBorder + 0] = ':';
	game[rBorder - 22][cBorder + 169] = ':';
	game[rBorder - 21][cBorder + 0] = '.';
	game[rBorder - 21][cBorder + 169] = '.';
	game[rBorder - 20][cBorder + 0] = '.';
	game[rBorder - 20][cBorder + 169] = '.';
	game[rBorder - 19][cBorder + 0] = ':';
	game[rBorder - 19][cBorder + 169] = ':';
	game[rBorder - 18][cBorder + 0] = ':';
	game[rBorder - 18][cBorder + 169] = ':';
	game[rBorder - 17][cBorder + 0] = '!';
	game[rBorder - 17][cBorder + 169] = '!';
	game[rBorder - 16][cBorder + 0] = '|';
	game[rBorder - 16][cBorder + 169] = '|';
	game[rBorder - 15][cBorder + 0] = '|';
	game[rBorder - 15][cBorder + 169] = '|';
	game[rBorder - 14][cBorder + 0] = '|';
	game[rBorder - 14][cBorder + 169] = '|';
	game[rBorder - 13][cBorder + 0] = '|';
	game[rBorder - 13][cBorder + 169] = '|';
	game[rBorder - 12][cBorder + 0] = '|';
	game[rBorder - 12][cBorder + 169] = '|';
	game[rBorder - 11][cBorder + 0] = ':';
	game[rBorder - 11][cBorder + 169] = ':';
	game[rBorder - 10][cBorder + 0] = ':';
	game[rBorder - 10][cBorder + 169] = ':';
	game[rBorder - 9][cBorder + 0] = '.';
	game[rBorder - 9][cBorder + 169] = '.';
	game[rBorder - 8][cBorder + 0] = '.';
	game[rBorder - 8][cBorder + 169] = '.';
	game[rBorder - 7][cBorder + 0] = ':';
	game[rBorder - 7][cBorder + 169] = ':';
	game[rBorder - 6][cBorder + 0] = ':';
	game[rBorder - 6][cBorder + 169] = '|';
	game[rBorder - 5][cBorder + 0] = '|';
	game[rBorder - 5][cBorder + 169] = '|';
	game[rBorder - 4][cBorder + 0] = '|';
	game[rBorder - 4][cBorder + 169] = '|';
	game[rBorder - 3][cBorder + 0] = '|';
	game[rBorder - 3][cBorder + 169] = '|';
	game[rBorder - 2][cBorder + 0] = '|';
	game[rBorder - 2][cBorder + 169] = '|';
	game[rBorder - 1][cBorder + 0] = '!';
	game[rBorder - 1][cBorder + 169] = '!';
}*/
void drawHero(char game[][350], int& rhero, int& chero) {
	game[rhero - 6][chero + 6] = '/';
	game[rhero - 6][chero + 7] = '\\';
	game[rhero - 6][chero + 8] = '_';
	game[rhero - 6][chero + 9] = '/';
	game[rhero - 6][chero + 10] = '\\';
	game[rhero - 5][chero + 1] = '/';
	game[rhero - 5][chero + 2] = '\\';
	game[rhero - 5][chero + 5] = '/';
	game[rhero - 5][chero + 7] = 'o';
	game[rhero - 5][chero + 9] = 'o';
	game[rhero - 5][chero + 11] = '\\';
	game[rhero - 4][chero + 0] = '/';
	game[rhero - 4][chero + 1] = '/';
	game[rhero - 4][chero + 2] = '\\';
	game[rhero - 4][chero + 3] = '\\';
	game[rhero - 4][chero + 5] = '\\';
	game[rhero - 4][chero + 6] = '~';
	game[rhero - 4][chero + 7] = '(';
	game[rhero - 4][chero + 8] = '*';
	game[rhero - 4][chero + 9] = ')';
	game[rhero - 4][chero + 10] = '~';
	game[rhero - 4][chero + 11] = '/';
	game[rhero - 3][chero + 0] = '`';
	game[rhero - 3][chero + 3] = '\\';
	game[rhero - 3][chero + 4] = '/';
	game[rhero - 3][chero + 8] = '^';
	game[rhero - 3][chero + 10] = '/';
	game[rhero - 2][chero + 3] = '|';
	game[rhero - 2][chero + 5] = '\\';
	game[rhero - 2][chero + 6] = '|';
	game[rhero - 2][chero + 7] = '|';
	game[rhero - 2][chero + 9] = '|';
	game[rhero - 2][chero + 10] = '|';
	game[rhero - 1][chero + 3] = '\\';
	game[rhero - 1][chero + 5] = '\'';
	game[rhero - 1][chero + 6] = '|';
	game[rhero - 1][chero + 7] = '|';
	game[rhero - 1][chero + 9] = '|';
	game[rhero - 1][chero + 10] = '|';
	game[rhero - 0][chero + 4] = '\\';
	game[rhero - 0][chero + 5] = ')';
	game[rhero - 0][chero + 6] = '(';
	game[rhero - 0][chero + 7] = ')';
	game[rhero - 0][chero + 8] = '-';
	game[rhero - 0][chero + 9] = '(';
	game[rhero - 0][chero + 10] = ')';
	game[rhero - 0][chero + 11] = ')';
}
void moveHero(int& rhero, int& chero, char move, char game[][350], int& scrollCstart, int& scrollCend, int& scrollRstart, int& scrollRend)
{
	if (move == 'w')
	{
		rhero --;
		/*
		scrollRstart --;
		scrollRend ++;
		*/
	}

	if (move == 'a')
	{
		chero--;
		scrollCstart--;
		scrollCend--;
	}
	if (move == 's' && game[rhero+1][chero] != '=')
	{
		rhero++;
		/*
		scrollRstart++;
		scrollRend++;
		*/
	}
	
	if (move == 'd')
	{
		chero ++;
		scrollCend++;
		scrollCstart++;
	}
	
	
}
void gravity(char game[][350], int& rHero, int&cHero, int & scrollRstart, int &scrollRend) {
	if (game[rHero+1][cHero] == ' ')
	{
		rHero++;
		/*
		scrollRstart--;
		scrollRend++;
		*/
	}
}
void drawEnemySpider(char game[][350], int enemy1r, int enemy1c) {
	game[enemy1r - 13][enemy1c + 14] = '(';
	game[enemy1r - 12][enemy1c + 15] = ')';
	game[enemy1r - 11][enemy1c + 14] = '(';
	game[enemy1r - 10][enemy1c + 8] = '/';
	game[enemy1r - 10][enemy1c + 9] = '\\';
	game[enemy1r - 10][enemy1c + 12] = '.';
	game[enemy1r - 10][enemy1c + 13] = '-';
	game[enemy1r - 10][enemy1c + 14] = '"';
	game[enemy1r - 10][enemy1c + 15] = '"';
	game[enemy1r - 10][enemy1c + 16] = '"';
	game[enemy1r - 10][enemy1c + 17] = '-';
	game[enemy1r - 10][enemy1c + 18] = '.';
	game[enemy1r - 10][enemy1c + 21] = '/';
	game[enemy1r - 10][enemy1c + 22] = '\\';
	game[enemy1r - 9][enemy1c + 7] = '/';
	game[enemy1r - 9][enemy1c + 8] = '/';
	game[enemy1r - 9][enemy1c + 9] = '\\';
	game[enemy1r - 9][enemy1c + 10] = '\\';
	game[enemy1r - 9][enemy1c + 11] = '/';
	game[enemy1r - 9][enemy1c + 14] = ',';
	game[enemy1r - 9][enemy1c + 15] = ',';
	game[enemy1r - 9][enemy1c + 16] = ',';
	game[enemy1r - 9][enemy1c + 19] = '\\';
	game[enemy1r - 9][enemy1c + 20] = '/';
	game[enemy1r - 9][enemy1c + 21] = '/';
	game[enemy1r - 9][enemy1c + 22] = '\\';
	game[enemy1r - 9][enemy1c + 23] = '\\';
	game[enemy1r - 8][enemy1c + 7] = '|';
	game[enemy1r - 8][enemy1c + 8] = '/';
	game[enemy1r - 8][enemy1c + 9] = '\\';
	game[enemy1r - 8][enemy1c + 10] = '|';
	game[enemy1r - 8][enemy1c + 12] = ',';
	game[enemy1r - 8][enemy1c + 13] = ';';
	game[enemy1r - 8][enemy1c + 14] = ';';
	game[enemy1r - 8][enemy1c + 15] = ';';
	game[enemy1r - 8][enemy1c + 16] = ';';
	game[enemy1r - 8][enemy1c + 17] = ';';
	game[enemy1r - 8][enemy1c + 18] = ',';
	game[enemy1r - 8][enemy1c + 20] = '|';
	game[enemy1r - 8][enemy1c + 21] = '/';
	game[enemy1r - 8][enemy1c + 22] = '\\';
	game[enemy1r - 8][enemy1c + 23] = '|';
	game[enemy1r - 7][enemy1c + 7] = '/';
	game[enemy1r - 7][enemy1c + 8] = '/';
	game[enemy1r - 7][enemy1c + 9] = '\\';
	game[enemy1r - 7][enemy1c + 10] = '\\';
	game[enemy1r - 7][enemy1c + 11] = '\\';
	game[enemy1r - 7][enemy1c + 12] = ';';
	game[enemy1r - 7][enemy1c + 13] = '-';
	game[enemy1r - 7][enemy1c + 14] = '"';
	game[enemy1r - 7][enemy1c + 15] = '"';
	game[enemy1r - 7][enemy1c + 16] = '"';
	game[enemy1r - 7][enemy1c + 17] = '-';
	game[enemy1r - 7][enemy1c + 18] = ';';
	game[enemy1r - 7][enemy1c + 19] = '/';
	game[enemy1r - 7][enemy1c + 20] = '/';
	game[enemy1r - 7][enemy1c + 21] = '/';
	game[enemy1r - 7][enemy1c + 22] = '\\';
	game[enemy1r - 7][enemy1c + 23] = '\\';
	game[enemy1r - 6][enemy1c + 6] = '/';
	game[enemy1r - 6][enemy1c + 7] = '/';
	game[enemy1r - 6][enemy1c + 10] = '\\';
	game[enemy1r - 6][enemy1c + 11] = '/';
	game[enemy1r - 6][enemy1c + 15] = '.';
	game[enemy1r - 6][enemy1c + 19] = '\\';
	game[enemy1r - 6][enemy1c + 20] = '/';
	game[enemy1r - 6][enemy1c + 23] = '\\';
	game[enemy1r - 6][enemy1c + 24] = '\\';
	game[enemy1r - 5][enemy1c + 5] = '(';
	game[enemy1r - 5][enemy1c + 6] = '|';
	game[enemy1r - 5][enemy1c + 8] = ',';
	game[enemy1r - 5][enemy1c + 9] = '-';
	game[enemy1r - 5][enemy1c + 10] = '_';
	game[enemy1r - 5][enemy1c + 11] = '|';
	game[enemy1r - 5][enemy1c + 13] = '\\';
	game[enemy1r - 5][enemy1c + 15] = '|';
	game[enemy1r - 5][enemy1c + 17] = '/';
	game[enemy1r - 5][enemy1c + 19] = '|';
	game[enemy1r - 5][enemy1c + 20] = '_';
	game[enemy1r - 5][enemy1c + 21] = '-';
	game[enemy1r - 5][enemy1c + 22] = ',';
	game[enemy1r - 5][enemy1c + 24] = '|';
	game[enemy1r - 5][enemy1c + 25] = ')';
	game[enemy1r - 4][enemy1c + 7] = '/';
	game[enemy1r - 4][enemy1c + 8] = '/';
	game[enemy1r - 4][enemy1c + 9] = '`';
	game[enemy1r - 4][enemy1c + 10] = '_';
	game[enemy1r - 4][enemy1c + 11] = '_';
	game[enemy1r - 4][enemy1c + 12] = '\\';
	game[enemy1r - 4][enemy1c + 13] = '.';
	game[enemy1r - 4][enemy1c + 14] = '-';
	game[enemy1r - 4][enemy1c + 15] = '.';
	game[enemy1r - 4][enemy1c + 16] = '-';
	game[enemy1r - 4][enemy1c + 17] = '.';
	game[enemy1r - 4][enemy1c + 18] = '/';
	game[enemy1r - 4][enemy1c + 19] = '_';
	game[enemy1r - 4][enemy1c + 20] = '_';
	game[enemy1r - 4][enemy1c + 21] = '`';
	game[enemy1r - 4][enemy1c + 22] = '\\';
	game[enemy1r - 4][enemy1c + 23] = '\\';
	game[enemy1r - 3][enemy1c + 6] = '/';
	game[enemy1r - 3][enemy1c + 7] = '/';
	game[enemy1r - 3][enemy1c + 9] = '/';
	game[enemy1r - 3][enemy1c + 10] = '.';
	game[enemy1r - 3][enemy1c + 11] = '-';
	game[enemy1r - 3][enemy1c + 12] = '(';
	game[enemy1r - 3][enemy1c + 13] = '(';
	game[enemy1r - 3][enemy1c + 14] = ')';
	game[enemy1r - 3][enemy1c + 16] = '(';
	game[enemy1r - 3][enemy1c + 17] = ')';
	game[enemy1r - 3][enemy1c + 18] = ')';
	game[enemy1r - 3][enemy1c + 19] = '-';
	game[enemy1r - 3][enemy1c + 20] = '.';
	game[enemy1r - 3][enemy1c + 21] = '\\';
	game[enemy1r - 3][enemy1c + 23] = '\\';
	game[enemy1r - 3][enemy1c + 24] = '\\';
	game[enemy1r - 2][enemy1c + 5] = '(';
	game[enemy1r - 2][enemy1c + 6] = '\\';
	game[enemy1r - 2][enemy1c + 8] = '|';
	game[enemy1r - 2][enemy1c + 9] = ')';
	game[enemy1r - 2][enemy1c + 13] = '\'';
	game[enemy1r - 2][enemy1c + 14] = '-';
	game[enemy1r - 2][enemy1c + 15] = '-';
	game[enemy1r - 2][enemy1c + 16] = '-';
	game[enemy1r - 2][enemy1c + 17] = '\'';
	game[enemy1r - 2][enemy1c + 21] = '(';
	game[enemy1r - 2][enemy1c + 22] = '|';
	game[enemy1r - 2][enemy1c + 24] = '/';
	game[enemy1r - 2][enemy1c + 25] = ')';
	game[enemy1r - 1][enemy1c + 6] = '`';
	game[enemy1r - 1][enemy1c + 8] = '(';
	game[enemy1r - 1][enemy1c + 9] = '|';
	game[enemy1r - 1][enemy1c + 21] = '|';
	game[enemy1r - 1][enemy1c + 22] = ')';
	game[enemy1r - 1][enemy1c + 24] = '`';
	game[enemy1r - 0][enemy1c + 8] = '\\';
	game[enemy1r - 0][enemy1c + 9] = ')';
	game[enemy1r - 0][enemy1c + 21] = '(';
	game[enemy1r - 0][enemy1c + 22] = '/';
}
void drawEnemyMouse(char game[][350], int enemyMouseR, int enemyMouseC) {
	game[enemyMouseR - 3][enemyMouseC + 7] = '(';
	game[enemyMouseR - 3][enemyMouseC + 8] = '`';
	game[enemyMouseR - 3][enemyMouseC + 9] = '-';
	game[enemyMouseR - 3][enemyMouseC + 10] = '(';
	game[enemyMouseR - 3][enemyMouseC + 11] = ')';
	game[enemyMouseR - 3][enemyMouseC + 12] = '_';
	game[enemyMouseR - 3][enemyMouseC + 13] = '.';
	game[enemyMouseR - 3][enemyMouseC + 14] = '-';
	game[enemyMouseR - 3][enemyMouseC + 15] = '=';
	game[enemyMouseR - 3][enemyMouseC + 16] = '-';
	game[enemyMouseR - 3][enemyMouseC + 17] = '.';
	game[enemyMouseR - 2][enemyMouseC + 7] = '/';
	game[enemyMouseR - 2][enemyMouseC + 8] = '6';
	game[enemyMouseR - 2][enemyMouseC + 9] = '6';
	game[enemyMouseR - 2][enemyMouseC + 12] = ',';
	game[enemyMouseR - 2][enemyMouseC + 15] = ',';
	game[enemyMouseR - 2][enemyMouseC + 18] = '\\';
	game[enemyMouseR - 1][enemyMouseC + 5] = '=';
	game[enemyMouseR - 1][enemyMouseC + 6] = '(';
	game[enemyMouseR - 1][enemyMouseC + 7] = 'o';
	game[enemyMouseR - 1][enemyMouseC + 8] = '_';
	game[enemyMouseR - 1][enemyMouseC + 9] = '/';
	game[enemyMouseR - 1][enemyMouseC + 10] = '=';
	game[enemyMouseR - 1][enemyMouseC + 11] = '/';
	game[enemyMouseR - 1][enemyMouseC + 12] = '/';
	game[enemyMouseR - 1][enemyMouseC + 13] = '_';
	game[enemyMouseR - 1][enemyMouseC + 14] = '(';
	game[enemyMouseR - 1][enemyMouseC + 18] = '/';
	game[enemyMouseR - 1][enemyMouseC + 19] = '=';
	game[enemyMouseR - 1][enemyMouseC + 20] = '=';
	game[enemyMouseR - 1][enemyMouseC + 21] = '=';
	game[enemyMouseR - 1][enemyMouseC + 22] = '=';
	game[enemyMouseR - 1][enemyMouseC + 23] = '=';
	game[enemyMouseR - 1][enemyMouseC + 24] = '=';
	game[enemyMouseR - 1][enemyMouseC + 25] = '`';
	game[enemyMouseR - 0][enemyMouseC + 9] = '~';
	game[enemyMouseR - 0][enemyMouseC + 10] = '"';
	game[enemyMouseR - 0][enemyMouseC + 11] = '`';
	game[enemyMouseR - 0][enemyMouseC + 13] = '~';
	game[enemyMouseR - 0][enemyMouseC + 14] = '"';
	game[enemyMouseR - 0][enemyMouseC + 15] = '~';
	game[enemyMouseR - 0][enemyMouseC + 16] = '~';
	game[enemyMouseR - 0][enemyMouseC + 17] = '`';

}
void drawEnemyDog(char game[][350], int renemy3, int cenemy3) {
	game[renemy3 - 4][cenemy3 + 3] = '_';
	game[renemy3 - 4][cenemy3 + 4] = '_';
	game[renemy3 - 3][cenemy3 + 0] = 'o';
	game[renemy3 - 3][cenemy3 + 1] = '-';
	game[renemy3 - 3][cenemy3 + 2] = '\'';
	game[renemy3 - 3][cenemy3 + 3] = '\'';
	game[renemy3 - 3][cenemy3 + 4] = '|';
	game[renemy3 - 3][cenemy3 + 5] = '\\';
	game[renemy3 - 3][cenemy3 + 6] = '_';
	game[renemy3 - 3][cenemy3 + 7] = '_';
	game[renemy3 - 3][cenemy3 + 8] = '_';
	game[renemy3 - 3][cenemy3 + 9] = '_';
	game[renemy3 - 3][cenemy3 + 10] = '_';
	game[renemy3 - 3][cenemy3 + 11] = '/';
	game[renemy3 - 3][cenemy3 + 12] = ')';
	game[renemy3 - 2][cenemy3 + 1] = '\\';
	game[renemy3 - 2][cenemy3 + 2] = '_';
	game[renemy3 - 2][cenemy3 + 3] = '/';
	game[renemy3 - 2][cenemy3 + 4] = '|';
	game[renemy3 - 2][cenemy3 + 5] = '_';
	game[renemy3 - 2][cenemy3 + 6] = ')';
	game[renemy3 - 2][cenemy3 + 12] = ')';
	game[renemy3 - 1][cenemy3 + 4] = '\\';
	game[renemy3 - 1][cenemy3 + 7] = '_';
	game[renemy3 - 1][cenemy3 + 8] = '_';
	game[renemy3 - 1][cenemy3 + 11] = '/';
	game[renemy3 - 0][cenemy3 + 4] = '(';
	game[renemy3 - 0][cenemy3 + 5] = '_';
	game[renemy3 - 0][cenemy3 + 6] = '/';
	game[renemy3 - 0][cenemy3 + 8] = '(';
	game[renemy3 - 0][cenemy3 + 9] = '_';
	game[renemy3 - 0][cenemy3 + 10] = '/';
}
void designTree2 (char game[][350], int designTree2r, int designTree2c) {
	game[designTree2r - 24][designTree2c + 12] = '.';
	game[designTree2r - 24][designTree2c + 21] = '+';
	game[designTree2r - 24][designTree2c + 32] = '.';
	game[designTree2r - 24][designTree2c + 39] = '.';
	game[designTree2r - 24][designTree2c + 50] = '.';
	game[designTree2r - 23][designTree2c + 5] = '.';
	game[designTree2r - 23][designTree2c + 18] = '_';
	game[designTree2r - 23][designTree2c + 27] = '.';
	game[designTree2r - 23][designTree2c + 48] = '.';
	game[designTree2r - 22][designTree2c + 2] = ',';
	game[designTree2r - 22][designTree2c + 17] = '/';
	game[designTree2r - 22][designTree2c + 18] = ';';
	game[designTree2r - 22][designTree2c + 19] = '-';
	game[designTree2r - 22][designTree2c + 20] = '.';
	game[designTree2r - 22][designTree2c + 21] = '_';
	game[designTree2r - 22][designTree2c + 22] = ',';
	game[designTree2r - 22][designTree2c + 23] = '-';
	game[designTree2r - 22][designTree2c + 24] = '.';
	game[designTree2r - 22][designTree2c + 25] = '_';
	game[designTree2r - 22][designTree2c + 26] = '_';
	game[designTree2r - 22][designTree2c + 27] = '_';
	game[designTree2r - 22][designTree2c + 28] = '_';
	game[designTree2r - 22][designTree2c + 37] = ',';
	game[designTree2r - 22][designTree2c + 38] = '-';
	game[designTree2r - 22][designTree2c + 39] = '-';
	game[designTree2r - 22][designTree2c + 40] = '-';
	game[designTree2r - 22][designTree2c + 41] = '-';
	game[designTree2r - 22][designTree2c + 42] = '-';
	game[designTree2r - 22][designTree2c + 43] = '.';
	game[designTree2r - 22][designTree2c + 44] = '_';
	game[designTree2r - 22][designTree2c + 45] = '_';
	game[designTree2r - 21][designTree2c + 1] = '(';
	game[designTree2r - 21][designTree2c + 2] = '(';
	game[designTree2r - 21][designTree2c + 11] = '.';
	game[designTree2r - 21][designTree2c + 16] = '(';
	game[designTree2r - 21][designTree2c + 17] = '_';
	game[designTree2r - 21][designTree2c + 18] = ':';
	game[designTree2r - 21][designTree2c + 19] = '#';
	game[designTree2r - 21][designTree2c + 20] = ':';
	game[designTree2r - 21][designTree2c + 21] = ':';
	game[designTree2r - 21][designTree2c + 22] = '_';
	game[designTree2r - 21][designTree2c + 23] = '.';
	game[designTree2r - 21][designTree2c + 24] = ':';
	game[designTree2r - 21][designTree2c + 25] = ':';
	game[designTree2r - 21][designTree2c + 26] = ':';
	game[designTree2r - 21][designTree2c + 27] = '.';
	game[designTree2r - 21][designTree2c + 29] = '`';
	game[designTree2r - 21][designTree2c + 30] = '-';
	game[designTree2r - 21][designTree2c + 31] = '.';
	game[designTree2r - 21][designTree2c + 32] = '_';
	game[designTree2r - 21][designTree2c + 36] = '/';
	game[designTree2r - 21][designTree2c + 37] = ':';
	game[designTree2r - 21][designTree2c + 38] = ',';
	game[designTree2r - 21][designTree2c + 40] = '/';
	game[designTree2r - 21][designTree2c + 41] = '-';
	game[designTree2r - 21][designTree2c + 42] = '.';
	game[designTree2r - 21][designTree2c + 43] = '_';
	game[designTree2r - 21][designTree2c + 44] = ',';
	game[designTree2r - 21][designTree2c + 46] = '`';
	game[designTree2r - 21][designTree2c + 47] = '.';
	game[designTree2r - 21][designTree2c + 48] = '_';
	game[designTree2r - 21][designTree2c + 49] = ',';
	game[designTree2r - 20][designTree2c + 2] = '`';
	game[designTree2r - 20][designTree2c + 20] = '\\';
	game[designTree2r - 20][designTree2c + 24] = '_';
	game[designTree2r - 20][designTree2c + 25] = '|';
	game[designTree2r - 20][designTree2c + 26] = '`';
	game[designTree2r - 20][designTree2c + 27] = '"';
	game[designTree2r - 20][designTree2c + 28] = '=';
	game[designTree2r - 20][designTree2c + 29] = ':';
	game[designTree2r - 20][designTree2c + 30] = '_';
	game[designTree2r - 20][designTree2c + 31] = ':';
	game[designTree2r - 20][designTree2c + 32] = ':';
	game[designTree2r - 20][designTree2c + 33] = '.';
	game[designTree2r - 20][designTree2c + 34] = '`';
	game[designTree2r - 20][designTree2c + 35] = '.';
	game[designTree2r - 20][designTree2c + 36] = ')';
	game[designTree2r - 20][designTree2c + 37] = ';';
	game[designTree2r - 20][designTree2c + 40] = '\\';
	game[designTree2r - 20][designTree2c + 42] = '_';
	game[designTree2r - 20][designTree2c + 43] = '_';
	game[designTree2r - 20][designTree2c + 44] = '/';
	game[designTree2r - 20][designTree2c + 46] = '/';
	game[designTree2r - 19][designTree2c + 22] = ',';
	game[designTree2r - 19][designTree2c + 27] = '`';
	game[designTree2r - 19][designTree2c + 28] = '.';
	game[designTree2r - 19][designTree2c + 29] = '/';
	game[designTree2r - 19][designTree2c + 32] = '\\';
	game[designTree2r - 19][designTree2c + 33] = ':';
	game[designTree2r - 19][designTree2c + 34] = '.';
	game[designTree2r - 19][designTree2c + 36] = '`';
	game[designTree2r - 19][designTree2c + 37] = '.';
	game[designTree2r - 19][designTree2c + 41] = ')';
	game[designTree2r - 19][designTree2c + 42] = '=';
	game[designTree2r - 19][designTree2c + 43] = '=';
	game[designTree2r - 19][designTree2c + 44] = '-';
	game[designTree2r - 19][designTree2c + 45] = '\'';
	game[designTree2r - 19][designTree2c + 48] = '.';
	game[designTree2r - 18][designTree2c + 4] = '.';
	game[designTree2r - 18][designTree2c + 11] = '.';
	game[designTree2r - 18][designTree2c + 12] = ',';
	game[designTree2r - 18][designTree2c + 14] = ',';
	game[designTree2r - 18][designTree2c + 15] = '-';
	game[designTree2r - 18][designTree2c + 16] = '=';
	game[designTree2r - 18][designTree2c + 17] = '-';
	game[designTree2r - 18][designTree2c + 18] = '.';
	game[designTree2r - 18][designTree2c + 21] = ',';
	game[designTree2r - 18][designTree2c + 22] = '\\';
	game[designTree2r - 18][designTree2c + 23] = ',';
	game[designTree2r - 18][designTree2c + 25] = '+';
	game[designTree2r - 18][designTree2c + 26] = '#';
	game[designTree2r - 18][designTree2c + 27] = '.';
	game[designTree2r - 18][designTree2c + 28] = '/';
	game[designTree2r - 18][designTree2c + 29] = '`';
	game[designTree2r - 18][designTree2c + 33] = '\\';
	game[designTree2r - 18][designTree2c + 34] = ':';
	game[designTree2r - 18][designTree2c + 35] = '.';
	game[designTree2r - 18][designTree2c + 38] = '/';
	game[designTree2r - 18][designTree2c + 40] = '/';
	game[designTree2r - 18][designTree2c + 52] = '.';
	game[designTree2r - 17][designTree2c + 0] = '.';
	game[designTree2r - 17][designTree2c + 12] = '\\';
	game[designTree2r - 17][designTree2c + 13] = '/';
	game[designTree2r - 17][designTree2c + 14] = ':';
	game[designTree2r - 17][designTree2c + 15] = '/';
	game[designTree2r - 17][designTree2c + 16] = '`';
	game[designTree2r - 17][designTree2c + 17] = '-';
	game[designTree2r - 17][designTree2c + 18] = '\'';
	game[designTree2r - 17][designTree2c + 20] = ',';
	game[designTree2r - 17][designTree2c + 22] = ',';
	game[designTree2r - 17][designTree2c + 23] = '\\';
	game[designTree2r - 17][designTree2c + 25] = '\'';
	game[designTree2r - 17][designTree2c + 26] = '`';
	game[designTree2r - 17][designTree2c + 28] = '`';
	game[designTree2r - 17][designTree2c + 30] = '`';
	game[designTree2r - 17][designTree2c + 34] = ')';
	game[designTree2r - 17][designTree2c + 35] = ':';
	game[designTree2r - 17][designTree2c + 37] = ',';
	game[designTree2r - 17][designTree2c + 39] = '/';
	game[designTree2r - 17][designTree2c + 40] = '_';
	game[designTree2r - 17][designTree2c + 43] = '-';
	game[designTree2r - 17][designTree2c + 44] = 'o';
	game[designTree2r - 16][designTree2c + 7] = '.';
	game[designTree2r - 16][designTree2c + 12] = '/';
	game[designTree2r - 16][designTree2c + 13] = ':';
	game[designTree2r - 16][designTree2c + 14] = '+';
	game[designTree2r - 16][designTree2c + 15] = '-';
	game[designTree2r - 16][designTree2c + 17] = '-';
	game[designTree2r - 16][designTree2c + 19] = '+';
	game[designTree2r - 16][designTree2c + 21] = '+';
	game[designTree2r - 16][designTree2c + 22] = '-';
	game[designTree2r - 16][designTree2c + 24] = ':';
	game[designTree2r - 16][designTree2c + 26] = ':';
	game[designTree2r - 16][designTree2c + 27] = '-';
	game[designTree2r - 16][designTree2c + 29] = '+';
	game[designTree2r - 16][designTree2c + 31] = '+';
	game[designTree2r - 16][designTree2c + 33] = '-';
	game[designTree2r - 16][designTree2c + 34] = ':';
	game[designTree2r - 16][designTree2c + 35] = '\'';
	game[designTree2r - 16][designTree2c + 38] = '/';
	game[designTree2r - 16][designTree2c + 39] = '(';
	game[designTree2r - 16][designTree2c + 40] = 'o';
	game[designTree2r - 16][designTree2c + 41] = '-';
	game[designTree2r - 16][designTree2c + 42] = ')';
	game[designTree2r - 16][designTree2c + 44] = '\\';
	game[designTree2r - 16][designTree2c + 45] = ')';
	game[designTree2r - 16][designTree2c + 51] = '.';
	game[designTree2r - 15][designTree2c + 2] = '.';
	game[designTree2r - 15][designTree2c + 9] = ',';
	game[designTree2r - 15][designTree2c + 10] = '=';
	game[designTree2r - 15][designTree2c + 11] = '\'';
	game[designTree2r - 15][designTree2c + 12] = ':';
	game[designTree2r - 15][designTree2c + 15] = '\\';
	game[designTree2r - 15][designTree2c + 20] = '`';
	game[designTree2r - 15][designTree2c + 22] = '`';
	game[designTree2r - 15][designTree2c + 23] = '/';
	game[designTree2r - 15][designTree2c + 24] = '`';
	game[designTree2r - 15][designTree2c + 26] = '\'';
	game[designTree2r - 15][designTree2c + 28] = ',';
	game[designTree2r - 15][designTree2c + 30] = ',';
	game[designTree2r - 15][designTree2c + 32] = ',';
	game[designTree2r - 15][designTree2c + 33] = ':';
	game[designTree2r - 15][designTree2c + 34] = '\'';
	game[designTree2r - 15][designTree2c + 36] = '`';
	game[designTree2r - 15][designTree2c + 37] = '\'';
	game[designTree2r - 15][designTree2c + 38] = '-';
	game[designTree2r - 15][designTree2c + 39] = '-';
	game[designTree2r - 15][designTree2c + 40] = '"';
	game[designTree2r - 15][designTree2c + 41] = '.';
	game[designTree2r - 15][designTree2c + 42] = '-';
	game[designTree2r - 15][designTree2c + 43] = '-';
	game[designTree2r - 15][designTree2c + 44] = '"';
	game[designTree2r - 15][designTree2c + 45] = '-';
	game[designTree2r - 15][designTree2c + 46] = '-';
	game[designTree2r - 15][designTree2c + 47] = '-';
	game[designTree2r - 15][designTree2c + 48] = '.';
	game[designTree2r - 15][designTree2c + 49] = '_';
	game[designTree2r - 15][designTree2c + 50] = '/';
	game[designTree2r - 15][designTree2c + 51] = '`';
	game[designTree2r - 15][designTree2c + 52] = '7';
	game[designTree2r - 14][designTree2c + 3] = '`';
	game[designTree2r - 14][designTree2c + 4] = '.';
	game[designTree2r - 14][designTree2c + 8] = '(';
	game[designTree2r - 14][designTree2c + 13] = '\\';
	game[designTree2r - 14][designTree2c + 14] = ':';
	game[designTree2r - 14][designTree2c + 16] = '\\';
	game[designTree2r - 14][designTree2c + 17] = ',';
	game[designTree2r - 14][designTree2c + 18] = '-';
	game[designTree2r - 14][designTree2c + 19] = '.';
	game[designTree2r - 14][designTree2c + 20] = '_';
	game[designTree2r - 14][designTree2c + 21] = '`';
	game[designTree2r - 14][designTree2c + 23] = '`';
	game[designTree2r - 14][designTree2c + 25] = '+';
	game[designTree2r - 14][designTree2c + 27] = '\'';
	game[designTree2r - 14][designTree2c + 28] = '\\';
	game[designTree2r - 14][designTree2c + 29] = ',';
	game[designTree2r - 14][designTree2c + 31] = ',';
	game[designTree2r - 14][designTree2c + 32] = '"';
	game[designTree2r - 14][designTree2c + 36] = '_';
	game[designTree2r - 14][designTree2c + 37] = ',';
	game[designTree2r - 14][designTree2c + 38] = '-';
	game[designTree2r - 14][designTree2c + 39] = '-';
	game[designTree2r - 14][designTree2c + 40] = '.';
	game[designTree2r - 14][designTree2c + 41] = '_';
	game[designTree2r - 14][designTree2c + 42] = ',';
	game[designTree2r - 14][designTree2c + 43] = '-';
	game[designTree2r - 14][designTree2c + 44] = '-';
	game[designTree2r - 14][designTree2c + 45] = '-';
	game[designTree2r - 14][designTree2c + 46] = '"';
	game[designTree2r - 14][designTree2c + 47] = ':';
	game[designTree2r - 14][designTree2c + 48] = '.';
	game[designTree2r - 14][designTree2c + 49] = '_';
	game[designTree2r - 14][designTree2c + 50] = '_';
	game[designTree2r - 14][designTree2c + 51] = '/';
	game[designTree2r - 13][designTree2c + 14] = '\\';
	game[designTree2r - 13][designTree2c + 15] = ':';
	game[designTree2r - 13][designTree2c + 18] = '`';
	game[designTree2r - 13][designTree2c + 21] = 'X';
	game[designTree2r - 13][designTree2c + 22] = '`';
	game[designTree2r - 13][designTree2c + 24] = '_';
	game[designTree2r - 13][designTree2c + 25] = '|';
	game[designTree2r - 13][designTree2c + 27] = '_';
	game[designTree2r - 13][designTree2c + 28] = ',';
	game[designTree2r - 13][designTree2c + 29] = '\\';
	game[designTree2r - 13][designTree2c + 30] = '/';
	game[designTree2r - 13][designTree2c + 31] = '\'';
	game[designTree2r - 13][designTree2c + 35] = '.';
	game[designTree2r - 13][designTree2c + 36] = '-';
	game[designTree2r - 13][designTree2c + 37] = '\'';
	game[designTree2r - 12][designTree2c + 0] = '.';
	game[designTree2r - 12][designTree2c + 16] = '"';
	game[designTree2r - 12][designTree2c + 17] = ':';
	game[designTree2r - 12][designTree2c + 18] = '.';
	game[designTree2r - 12][designTree2c + 19] = '_';
	game[designTree2r - 12][designTree2c + 20] = ':';
	game[designTree2r - 12][designTree2c + 21] = '`';
	game[designTree2r - 12][designTree2c + 22] = '\\';
	game[designTree2r - 12][designTree2c + 23] = '_';
	game[designTree2r - 12][designTree2c + 24] = '_';
	game[designTree2r - 12][designTree2c + 25] = '_';
	game[designTree2r - 12][designTree2c + 26] = '_';
	game[designTree2r - 12][designTree2c + 29] = '/';
	game[designTree2r - 12][designTree2c + 30] = ':';
	game[designTree2r - 12][designTree2c + 31] = '\'';
	game[designTree2r - 12][designTree2c + 34] = '/';
	game[designTree2r - 12][designTree2c + 41] = '.';
	game[designTree2r - 12][designTree2c + 53] = '.';
	game[designTree2r - 11][designTree2c + 20] = '\\';
	game[designTree2r - 11][designTree2c + 21] = ':';
	game[designTree2r - 11][designTree2c + 22] = ':';
	game[designTree2r - 11][designTree2c + 23] = '.';
	game[designTree2r - 11][designTree2c + 26] = ':';
	game[designTree2r - 11][designTree2c + 27] = '\\';
	game[designTree2r - 11][designTree2c + 28] = '/';
	game[designTree2r - 11][designTree2c + 29] = ':';
	game[designTree2r - 11][designTree2c + 30] = '\'';
	game[designTree2r - 11][designTree2c + 33] = '/';
	game[designTree2r - 11][designTree2c + 48] = '+';
	game[designTree2r - 10][designTree2c + 3] = '.';
	game[designTree2r - 10][designTree2c + 21] = '`';
	game[designTree2r - 10][designTree2c + 22] = '.';
	game[designTree2r - 10][designTree2c + 23] = ':';
	game[designTree2r - 10][designTree2c + 24] = '.';
	game[designTree2r - 10][designTree2c + 27] = '/';
	game[designTree2r - 10][designTree2c + 28] = ':';
	game[designTree2r - 10][designTree2c + 29] = '\'';
	game[designTree2r - 10][designTree2c + 32] = '}';
	game[designTree2r - 10][designTree2c + 39] = '.';
	game[designTree2r - 9][designTree2c + 11] = '.';
	game[designTree2r - 9][designTree2c + 23] = ')';
	game[designTree2r - 9][designTree2c + 24] = ':';
	game[designTree2r - 9][designTree2c + 25] = '_';
	game[designTree2r - 9][designTree2c + 26] = '(';
	game[designTree2r - 9][designTree2c + 27] = ':';
	game[designTree2r - 9][designTree2c + 28] = ';';
	game[designTree2r - 9][designTree2c + 32] = '\\';
	game[designTree2r - 9][designTree2c + 44] = '.';
	game[designTree2r - 8][designTree2c + 22] = '/';
	game[designTree2r - 8][designTree2c + 23] = ':';
	game[designTree2r - 8][designTree2c + 24] = '.';
	game[designTree2r - 8][designTree2c + 26] = '_';
	game[designTree2r - 8][designTree2c + 27] = '/';
	game[designTree2r - 8][designTree2c + 29] = ',';
	game[designTree2r - 8][designTree2c + 32] = '|';
	game[designTree2r - 7][designTree2c + 19] = '.';
	game[designTree2r - 7][designTree2c + 21] = '(';
	game[designTree2r - 7][designTree2c + 22] = '|';
	game[designTree2r - 7][designTree2c + 23] = ':';
	game[designTree2r - 7][designTree2c + 24] = ':';
	game[designTree2r - 7][designTree2c + 25] = '.';
	game[designTree2r - 7][designTree2c + 31] = ',';
	game[designTree2r - 7][designTree2c + 32] = '`';
	game[designTree2r - 7][designTree2c + 51] = '.';
	game[designTree2r - 6][designTree2c + 5] = '.';
	game[designTree2r - 6][designTree2c + 22] = '|';
	game[designTree2r - 6][designTree2c + 23] = ':';
	game[designTree2r - 6][designTree2c + 24] = ':';
	game[designTree2r - 6][designTree2c + 25] = '.';
	game[designTree2r - 6][designTree2c + 30] = '{';
	game[designTree2r - 6][designTree2c + 31] = '\\';
	game[designTree2r - 5][designTree2c + 22] = '|';
	game[designTree2r - 5][designTree2c + 23] = ':';
	game[designTree2r - 5][designTree2c + 24] = ':';
	game[designTree2r - 5][designTree2c + 25] = '.';
	game[designTree2r - 5][designTree2c + 26] = '\\';
	game[designTree2r - 5][designTree2c + 29] = '\\';
	game[designTree2r - 5][designTree2c + 31] = '`';
	game[designTree2r - 5][designTree2c + 32] = '.';
	game[designTree2r - 4][designTree2c + 22] = '|';
	game[designTree2r - 4][designTree2c + 23] = ':';
	game[designTree2r - 4][designTree2c + 24] = ':';
	game[designTree2r - 4][designTree2c + 25] = ':';
	game[designTree2r - 4][designTree2c + 26] = '(';
	game[designTree2r - 4][designTree2c + 27] = '\\';
	game[designTree2r - 4][designTree2c + 32] = '|';
	game[designTree2r - 3][designTree2c + 14] = 'O';
	game[designTree2r - 3][designTree2c + 22] = '|';
	game[designTree2r - 3][designTree2c + 23] = ':';
	game[designTree2r - 3][designTree2c + 24] = ':';
	game[designTree2r - 3][designTree2c + 25] = ':';
	game[designTree2r - 3][designTree2c + 26] = '/';
	game[designTree2r - 3][designTree2c + 27] = '{';
	game[designTree2r - 3][designTree2c + 29] = '}';
	game[designTree2r - 3][designTree2c + 32] = '|';
	game[designTree2r - 3][designTree2c + 51] = '(';
	game[designTree2r - 3][designTree2c + 52] = 'o';
	game[designTree2r - 2][designTree2c + 15] = ')';
	game[designTree2r - 2][designTree2c + 18] = '_';
	game[designTree2r - 2][designTree2c + 19] = '_';
	game[designTree2r - 2][designTree2c + 20] = '_';
	game[designTree2r - 2][designTree2c + 21] = '/';
	game[designTree2r - 2][designTree2c + 22] = '#';
	game[designTree2r - 2][designTree2c + 23] = '\\';
	game[designTree2r - 2][designTree2c + 24] = ':';
	game[designTree2r - 2][designTree2c + 25] = ':';
	game[designTree2r - 2][designTree2c + 26] = '`';
	game[designTree2r - 2][designTree2c + 27] = '/';
	game[designTree2r - 2][designTree2c + 29] = '(';
	game[designTree2r - 2][designTree2c + 30] = 'O';
	game[designTree2r - 2][designTree2c + 32] = '"';
	game[designTree2r - 2][designTree2c + 33] = '=';
	game[designTree2r - 2][designTree2c + 34] = '=';
	game[designTree2r - 2][designTree2c + 35] = '.';
	game[designTree2r - 2][designTree2c + 36] = '_';
	game[designTree2r - 2][designTree2c + 37] = '_';
	game[designTree2r - 2][designTree2c + 38] = '_';
	game[designTree2r - 2][designTree2c + 39] = '_';
	game[designTree2r - 2][designTree2c + 40] = '_';
	game[designTree2r - 2][designTree2c + 44] = 'O';
	game[designTree2r - 2][designTree2c + 45] = ',';
	game[designTree2r - 2][designTree2c + 47] = '(';
	game[designTree2r - 2][designTree2c + 48] = 'O';
	game[designTree2r - 2][designTree2c + 51] = '/';
	game[designTree2r - 2][designTree2c + 52] = '`';
	game[designTree2r - 1][designTree2c + 10] = '~';
	game[designTree2r - 1][designTree2c + 11] = '~';
	game[designTree2r - 1][designTree2c + 12] = '~';
	game[designTree2r - 1][designTree2c + 13] = 'w';
	game[designTree2r - 1][designTree2c + 14] = '/';
	game[designTree2r - 1][designTree2c + 15] = 'w';
	game[designTree2r - 1][designTree2c + 16] = '~';
	game[designTree2r - 1][designTree2c + 17] = '"';
	game[designTree2r - 1][designTree2c + 18] = '~';
	game[designTree2r - 1][designTree2c + 19] = '~';
	game[designTree2r - 1][designTree2c + 20] = ',';
	game[designTree2r - 1][designTree2c + 21] = '\\';
	game[designTree2r - 1][designTree2c + 22] = '`';
	game[designTree2r - 1][designTree2c + 24] = '`';
	game[designTree2r - 1][designTree2c + 25] = ':';
	game[designTree2r - 1][designTree2c + 26] = '/';
	game[designTree2r - 1][designTree2c + 27] = ',';
	game[designTree2r - 1][designTree2c + 28] = '-';
	game[designTree2r - 1][designTree2c + 29] = '(';
	game[designTree2r - 1][designTree2c + 30] = '~';
	game[designTree2r - 1][designTree2c + 31] = '`';
	game[designTree2r - 1][designTree2c + 32] = '"';
	game[designTree2r - 1][designTree2c + 33] = '~';
	game[designTree2r - 1][designTree2c + 34] = '~';
	game[designTree2r - 1][designTree2c + 35] = '~';
	game[designTree2r - 1][designTree2c + 36] = '~';
	game[designTree2r - 1][designTree2c + 37] = '~';
	game[designTree2r - 1][designTree2c + 38] = '~';
	game[designTree2r - 1][designTree2c + 39] = '~';
	game[designTree2r - 1][designTree2c + 40] = '~';
	game[designTree2r - 1][designTree2c + 41] = '"';
	game[designTree2r - 1][designTree2c + 42] = '~';
	game[designTree2r - 1][designTree2c + 43] = 'o';
	game[designTree2r - 1][designTree2c + 44] = '~';
	game[designTree2r - 1][designTree2c + 45] = '\\';
	game[designTree2r - 1][designTree2c + 46] = '~';
	game[designTree2r - 1][designTree2c + 47] = '/';
	game[designTree2r - 1][designTree2c + 48] = '~';
	game[designTree2r - 1][designTree2c + 49] = 'w';
	game[designTree2r - 1][designTree2c + 50] = '|';
	game[designTree2r - 1][designTree2c + 51] = '/';
	game[designTree2r - 1][designTree2c + 52] = '~';
	game[designTree2r - 0][designTree2c + 6] = '~';
	game[designTree2r - 0][designTree2c + 7] = '~';
	game[designTree2r - 0][designTree2c + 8] = '~';
	game[designTree2r - 0][designTree2c + 9] = '~';
	game[designTree2r - 0][designTree2c + 10] = '~';
	game[designTree2r - 0][designTree2c + 11] = '~';
	game[designTree2r - 0][designTree2c + 12] = '~';
	game[designTree2r - 0][designTree2c + 13] = '~';
	game[designTree2r - 0][designTree2c + 14] = '~';
	game[designTree2r - 0][designTree2c + 15] = '~';
	game[designTree2r - 0][designTree2c + 16] = '~';
	game[designTree2r - 0][designTree2c + 17] = '~';
	game[designTree2r - 0][designTree2c + 18] = '~';
	game[designTree2r - 0][designTree2c + 19] = '~';
	game[designTree2r - 0][designTree2c + 20] = '~';
	game[designTree2r - 0][designTree2c + 21] = '~';
	game[designTree2r - 0][designTree2c + 22] = '~';
	game[designTree2r - 0][designTree2c + 23] = '~';
	game[designTree2r - 0][designTree2c + 24] = '~';
	game[designTree2r - 0][designTree2c + 25] = '~';
	game[designTree2r - 0][designTree2c + 26] = '~';
	game[designTree2r - 0][designTree2c + 27] = '~';
	game[designTree2r - 0][designTree2c + 28] = '~';
	game[designTree2r - 0][designTree2c + 29] = '\\';
	game[designTree2r - 0][designTree2c + 30] = '\\';
	game[designTree2r - 0][designTree2c + 31] = 'W';
	game[designTree2r - 0][designTree2c + 32] = '~';
	game[designTree2r - 0][designTree2c + 33] = '~';
	game[designTree2r - 0][designTree2c + 34] = '~';
	game[designTree2r - 0][designTree2c + 35] = '~';
	game[designTree2r - 0][designTree2c + 36] = '~';
	game[designTree2r - 0][designTree2c + 37] = '~';
	game[designTree2r - 0][designTree2c + 38] = '~';
	game[designTree2r - 0][designTree2c + 39] = '~';
	game[designTree2r - 0][designTree2c + 40] = '~';
	game[designTree2r - 0][designTree2c + 41] = '~';
	game[designTree2r - 0][designTree2c + 42] = '~';
	game[designTree2r - 0][designTree2c + 43] = '~';
	game[designTree2r - 0][designTree2c + 44] = '\\';
	game[designTree2r - 0][designTree2c + 45] = '|';
	game[designTree2r - 0][designTree2c + 46] = '/';
	game[designTree2r - 0][designTree2c + 47] = '~';
	game[designTree2r - 0][designTree2c + 48] = '~';

}
void laser(char game[][350], int rLaser, int cLaser, int &chero) {
	if (chero == 59 || chero == 60 || chero == 62
		|| chero == 64 || chero == 66 || chero == 68 || chero == 70 || chero == 72 || chero == 74
		|| chero == 76)
	{
		game[rLaser - 20][cLaser + 31] = '#';
		game[rLaser - 20][cLaser + 32] = '%';
		game[rLaser - 20][cLaser + 33] = ':';
		game[rLaser - 20][cLaser + 41] = '  ';
		game[rLaser - 19][cLaser + 30] = '+';
		game[rLaser - 19][cLaser + 31] = '%';
		game[rLaser - 19][cLaser + 32] = '%';
		game[rLaser - 19][cLaser + 33] = '#';
		game[rLaser - 19][cLaser + 34] = '.';
		game[rLaser - 18][cLaser + 31] = '+';
		game[rLaser - 18][cLaser + 32] = '#';
		game[rLaser - 17][cLaser + 30] = '=';
		game[rLaser - 17][cLaser + 31] = '%';
		game[rLaser - 17][cLaser + 32] = '%';
		game[rLaser - 17][cLaser + 33] = '+';
		game[rLaser - 16][cLaser + 30] = '-';
		game[rLaser - 16][cLaser + 31] = '%';
		game[rLaser - 16][cLaser + 32] = '%';
		game[rLaser - 16][cLaser + 33] = '-';
		game[rLaser - 15][cLaser + 31] = '*';
		game[rLaser - 15][cLaser + 32] = '%';
		game[rLaser - 14][cLaser + 30] = '+';
		game[rLaser - 14][cLaser + 31] = '%';
		game[rLaser - 14][cLaser + 32] = '%';
		game[rLaser - 14][cLaser + 33] = '%';
		game[rLaser - 13][cLaser + 31] = ':';
		game[rLaser - 12][cLaser + 30] = '+';
		game[rLaser - 12][cLaser + 31] = '#';
		game[rLaser - 12][cLaser + 32] = '#';
		game[rLaser - 12][cLaser + 33] = '+';
		game[rLaser - 11][cLaser + 30] = '+';
		game[rLaser - 11][cLaser + 31] = '%';
		game[rLaser - 11][cLaser + 32] = '%';
		game[rLaser - 11][cLaser + 33] = ':';
		game[rLaser - 10][cLaser + 30] = '.';
		game[rLaser - 10][cLaser + 31] = '#';
		game[rLaser - 10][cLaser + 32] = '#';
		game[rLaser - 9][cLaser + 30] = ':';
		game[rLaser - 9][cLaser + 31] = '#';
		game[rLaser - 9][cLaser + 32] = '%';
		game[rLaser - 9][cLaser + 33] = '*';
		game[rLaser - 8][cLaser + 30] = '.';
		game[rLaser - 8][cLaser + 31] = '*';
		game[rLaser - 8][cLaser + 32] = '#';
		game[rLaser - 7][cLaser + 31] = '-';
		game[rLaser - 7][cLaser + 32] = ':';
		game[rLaser - 6][cLaser + 30] = '=';
		game[rLaser - 6][cLaser + 31] = '#';
		game[rLaser - 6][cLaser + 32] = '#';
		game[rLaser - 6][cLaser + 33] = ':';
		game[rLaser - 5][cLaser + 30] = '-';
		game[rLaser - 5][cLaser + 31] = '#';
		game[rLaser - 5][cLaser + 32] = '*';
		game[rLaser - 5][cLaser + 33] = '=';
		game[rLaser - 4][cLaser + 32] = '.';
		game[rLaser - 3][cLaser + 30] = '+';
		game[rLaser - 3][cLaser + 31] = '#';
		game[rLaser - 3][cLaser + 32] = '%';
		game[rLaser - 3][cLaser + 33] = '*';
		game[rLaser - 1][cLaser + 31] = '.';
		game[rLaser - 1][cLaser + 32] = ':';
	}
}
/*
void elevator(char game[][350] , int rElevator, int cElevator) {
	game[rElevator - 16][cElevator + 0] = '_';
	game[rElevator - 16][cElevator + 1] = '_';
	game[rElevator - 16][cElevator + 2] = '_';
	game[rElevator - 16][cElevator + 3] = '_';
	game[rElevator - 16][cElevator + 4] = '_';
	game[rElevator - 16][cElevator + 5] = '_';
	game[rElevator - 16][cElevator + 6] = '_';
	game[rElevator - 16][cElevator + 7] = '_';
	game[rElevator - 16][cElevator + 8] = '_';
	game[rElevator - 16][cElevator + 9] = '_';
	game[rElevator - 16][cElevator + 10] = '_';
	game[rElevator - 16][cElevator + 11] = '_';
	game[rElevator - 16][cElevator + 12] = '_';
	game[rElevator - 16][cElevator + 13] = '_';
	game[rElevator - 16][cElevator + 14] = '_';
	game[rElevator - 16][cElevator + 15] = '_';
	game[rElevator - 16][cElevator + 16] = '_';
	game[rElevator - 16][cElevator + 17] = '_';
	game[rElevator - 16][cElevator + 18] = '_';
	game[rElevator - 16][cElevator + 19] = '_';
	game[rElevator - 16][cElevator + 20] = '_';
	game[rElevator - 16][cElevator + 21] = '_';
	game[rElevator - 16][cElevator + 22] = '_';
	game[rElevator - 16][cElevator + 23] = '_';
	game[rElevator - 16][cElevator + 24] = '_';
	game[rElevator - 16][cElevator + 25] = '_';
	game[rElevator - 15][cElevator + 0] = '|';
	game[rElevator - 15][cElevator + 25] = '|';
	game[rElevator - 14][cElevator + 0] = '|';
	game[rElevator - 14][cElevator + 25] = '|';
	game[rElevator - 13][cElevator + 0] = '|';
	game[rElevator - 13][cElevator + 25] = '|';
	game[rElevator - 12][cElevator + 0] = '|';
	game[rElevator - 12][cElevator + 25] = '|';
	game[rElevator - 11][cElevator + 0] = '|';
	game[rElevator - 11][cElevator + 25] = '|';
	game[rElevator - 10][cElevator + 0] = '|';
	game[rElevator - 10][cElevator + 25] = '|';
	game[rElevator - 9][cElevator + 0] = '|';
	game[rElevator - 9][cElevator + 25] = '|';
	game[rElevator - 8][cElevator + 0] = '|';
	game[rElevator - 8][cElevator + 25] = '|';
	game[rElevator - 0][cElevator + 0] = '_';
	game[rElevator - 0][cElevator + 1] = '_';
	game[rElevator - 0][cElevator + 2] = '_';
	game[rElevator - 0][cElevator + 3] = '_';
	game[rElevator - 0][cElevator + 4] = '_';
	game[rElevator - 0][cElevator + 5] = '_';
	game[rElevator - 0][cElevator + 6] = '_';
	game[rElevator - 0][cElevator + 7] = '_';
	game[rElevator - 0][cElevator + 8] = '_';
	game[rElevator - 0][cElevator + 9] = '_';
	game[rElevator - 0][cElevator + 10] = '_';
	game[rElevator - 0][cElevator + 11] = '_';
	game[rElevator - 0][cElevator + 12] = '_';
	game[rElevator - 0][cElevator + 13] = '_';
	game[rElevator - 0][cElevator + 14] = '_';
	game[rElevator - 0][cElevator + 15] = '_';
	game[rElevator - 0][cElevator + 16] = '_';
	game[rElevator - 0][cElevator + 17] = '_';
	game[rElevator - 0][cElevator + 18] = '_';
	game[rElevator - 0][cElevator + 19] = '_';
	game[rElevator - 0][cElevator + 20] = '_';
	game[rElevator - 0][cElevator + 21] = '_';
	game[rElevator - 0][cElevator + 22] = '_';
	game[rElevator - 0][cElevator + 23] = '_';
}
*/
void singleBullet(char game[][350], int &sBulletR, int &sBulletC, int chero, int enemyMouseC) {
	if (chero == 100)
	{
		for (int i = enemyMouseC - 1; i > 0; i--)
		{
				int temp = game[sBulletR][i] = '+';
		}
	}
}

void main() {
	char game[30][350];
	int rhero = 26, chero = 30, platformR = 27, platformC = 2, designTree2r = 27, designTree2c = -2; //rBorder = 0, cBorder = 350
	int enemySpiderR = 0, enemySpiderC = 60, enemyMouseR = 27, enemyMouseC = 130, enemyDogR = 27, enemyDogC = 200;
	char move=NULL;
	int rLaser = 24, cLaser = 44, sBulletR = 25, sBulletC = 129;
	int scrollCstart = 0, scrollCend = 120, scrollRstart = 30, scrollRend = 0;//SCROLL UP BROKEN
	int rElevator = 26, cElevator = 150;


	while(1) {
		while (!_kbhit()) {
			Empty(game);
			drawPlatform(game, platformR, platformC);
			//elevator(game, rElevator, cElevator);
			designTree2(game, designTree2r, designTree2c);
			drawHero(game, rhero, chero);
			drawEnemySpider(game, enemySpiderR, enemySpiderC);
			laser(game, rLaser, cLaser, chero);
			drawEnemyMouse(game, enemyMouseR, enemyMouseC);
			singleBullet(game, sBulletR, sBulletC, chero, enemyMouseC);
			drawEnemyDog(game, enemyDogR, enemyDogC);
			drawGame(game, scrollCend, scrollCstart, scrollRstart, scrollRend);
			//Border(game, rBorder, cBorder);
			gravity(game, rhero, chero, scrollRstart, scrollRend);
			Sleep(100);

		}
		move = _getch();
		moveHero(rhero, chero, move, game, scrollCstart, scrollCend, scrollRstart, scrollRend);
	}
}